package com.cy.store.vo;

public class ReviewVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.rid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.oid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.pid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.uid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer uid;
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.score
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Byte score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private String review;

    public Integer getRid() {
        return rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    public Integer getOid() {
        return oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Byte getScore() {
        return score;
    }

    public void setScore(Byte score) {
        this.score = score;
    }

    public String getReview() {
        return review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    @Override
    public String toString() {
        return "ReviewVO{" +
                "rid=" + rid +
                ", oid=" + oid +
                ", pid=" + pid +
                ", uid=" + uid +
                ", username='" + username + '\'' +
                ", score=" + score +
                ", review='" + review + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ReviewVO)) return false;

        ReviewVO reviewVO = (ReviewVO) o;

        if (getRid() != null ? !getRid().equals(reviewVO.getRid()) : reviewVO.getRid() != null) return false;
        if (getOid() != null ? !getOid().equals(reviewVO.getOid()) : reviewVO.getOid() != null) return false;
        if (getPid() != null ? !getPid().equals(reviewVO.getPid()) : reviewVO.getPid() != null) return false;
        if (getUid() != null ? !getUid().equals(reviewVO.getUid()) : reviewVO.getUid() != null) return false;
        if (getUsername() != null ? !getUsername().equals(reviewVO.getUsername()) : reviewVO.getUsername() != null)
            return false;
        if (getScore() != null ? !getScore().equals(reviewVO.getScore()) : reviewVO.getScore() != null) return false;
        return getReview() != null ? getReview().equals(reviewVO.getReview()) : reviewVO.getReview() == null;
    }

    @Override
    public int hashCode() {
        int result = getRid() != null ? getRid().hashCode() : 0;
        result = 31 * result + (getOid() != null ? getOid().hashCode() : 0);
        result = 31 * result + (getPid() != null ? getPid().hashCode() : 0);
        result = 31 * result + (getUid() != null ? getUid().hashCode() : 0);
        result = 31 * result + (getUsername() != null ? getUsername().hashCode() : 0);
        result = 31 * result + (getScore() != null ? getScore().hashCode() : 0);
        result = 31 * result + (getReview() != null ? getReview().hashCode() : 0);
        return result;
    }
}
