package com.cy.store.entity;

import java.util.Date;

public class DesignOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.did
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.uid
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.style
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.area
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.layout
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String layout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.budget
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.phone
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.intro
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.created_time
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.status
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.did
     *
     * @return the value of t_design_order.did
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.did
     *
     * @param did the value for t_design_order.did
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.uid
     *
     * @return the value of t_design_order.uid
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.uid
     *
     * @param uid the value for t_design_order.uid
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.style
     *
     * @return the value of t_design_order.style
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.style
     *
     * @param style the value for t_design_order.style
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.area
     *
     * @return the value of t_design_order.area
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.area
     *
     * @param area the value for t_design_order.area
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.layout
     *
     * @return the value of t_design_order.layout
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getLayout() {
        return layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.layout
     *
     * @param layout the value for t_design_order.layout
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setLayout(String layout) {
        this.layout = layout == null ? null : layout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.budget
     *
     * @return the value of t_design_order.budget
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.budget
     *
     * @param budget the value for t_design_order.budget
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setBudget(String budget) {
        this.budget = budget == null ? null : budget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.phone
     *
     * @return the value of t_design_order.phone
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.phone
     *
     * @param phone the value for t_design_order.phone
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.intro
     *
     * @return the value of t_design_order.intro
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.intro
     *
     * @param intro the value for t_design_order.intro
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.created_time
     *
     * @return the value of t_design_order.created_time
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.created_time
     *
     * @param createdTime the value for t_design_order.created_time
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_design_order.status
     *
     * @return the value of t_design_order.status
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_design_order.status
     *
     * @param status the value for t_design_order.status
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "DesignOrder{" +
                "did=" + did +
                ", uid=" + uid +
                ", style='" + style + '\'' +
                ", area='" + area + '\'' +
                ", layout='" + layout + '\'' +
                ", budget='" + budget + '\'' +
                ", phone='" + phone + '\'' +
                ", intro='" + intro + '\'' +
                ", createdTime=" + createdTime +
                ", status=" + status +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DesignOrder)) return false;

        DesignOrder that = (DesignOrder) o;

        if (getDid() != null ? !getDid().equals(that.getDid()) : that.getDid() != null) return false;
        if (getUid() != null ? !getUid().equals(that.getUid()) : that.getUid() != null) return false;
        if (getStyle() != null ? !getStyle().equals(that.getStyle()) : that.getStyle() != null) return false;
        if (getArea() != null ? !getArea().equals(that.getArea()) : that.getArea() != null) return false;
        if (getLayout() != null ? !getLayout().equals(that.getLayout()) : that.getLayout() != null) return false;
        if (getBudget() != null ? !getBudget().equals(that.getBudget()) : that.getBudget() != null) return false;
        if (getPhone() != null ? !getPhone().equals(that.getPhone()) : that.getPhone() != null) return false;
        if (getIntro() != null ? !getIntro().equals(that.getIntro()) : that.getIntro() != null) return false;
        if (getCreatedTime() != null ? !getCreatedTime().equals(that.getCreatedTime()) : that.getCreatedTime() != null)
            return false;
        return getStatus() != null ? getStatus().equals(that.getStatus()) : that.getStatus() == null;
    }

    @Override
    public int hashCode() {
        int result = getDid() != null ? getDid().hashCode() : 0;
        result = 31 * result + (getUid() != null ? getUid().hashCode() : 0);
        result = 31 * result + (getStyle() != null ? getStyle().hashCode() : 0);
        result = 31 * result + (getArea() != null ? getArea().hashCode() : 0);
        result = 31 * result + (getLayout() != null ? getLayout().hashCode() : 0);
        result = 31 * result + (getBudget() != null ? getBudget().hashCode() : 0);
        result = 31 * result + (getPhone() != null ? getPhone().hashCode() : 0);
        result = 31 * result + (getIntro() != null ? getIntro().hashCode() : 0);
        result = 31 * result + (getCreatedTime() != null ? getCreatedTime().hashCode() : 0);
        result = 31 * result + (getStatus() != null ? getStatus().hashCode() : 0);
        return result;
    }
}