package com.cy.store.entity;

import java.util.Date;

public class DesignOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.did
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.uid
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer uid;
    private String name;
    private Integer designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.style
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.area
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.layout
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String layout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.budget
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.phone
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.intro
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.created_time
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_design_order.status
     *
     * @mbggenerated Wed Apr 19 22:48:44 CST 2023
     */
    private Integer status;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DesignOrder)) return false;

        DesignOrder that = (DesignOrder) o;

        if (getDid() != null ? !getDid().equals(that.getDid()) : that.getDid() != null) return false;
        if (getUid() != null ? !getUid().equals(that.getUid()) : that.getUid() != null) return false;
        if (getName() != null ? !getName().equals(that.getName()) : that.getName() != null) return false;
        if (getDesignerId() != null ? !getDesignerId().equals(that.getDesignerId()) : that.getDesignerId() != null)
            return false;
        if (getStyle() != null ? !getStyle().equals(that.getStyle()) : that.getStyle() != null) return false;
        if (getArea() != null ? !getArea().equals(that.getArea()) : that.getArea() != null) return false;
        if (getLayout() != null ? !getLayout().equals(that.getLayout()) : that.getLayout() != null) return false;
        if (getBudget() != null ? !getBudget().equals(that.getBudget()) : that.getBudget() != null) return false;
        if (getPhone() != null ? !getPhone().equals(that.getPhone()) : that.getPhone() != null) return false;
        if (getIntro() != null ? !getIntro().equals(that.getIntro()) : that.getIntro() != null) return false;
        if (getCreatedTime() != null ? !getCreatedTime().equals(that.getCreatedTime()) : that.getCreatedTime() != null)
            return false;
        return getStatus() != null ? getStatus().equals(that.getStatus()) : that.getStatus() == null;
    }

    @Override
    public int hashCode() {
        int result = getDid() != null ? getDid().hashCode() : 0;
        result = 31 * result + (getUid() != null ? getUid().hashCode() : 0);
        result = 31 * result + (getName() != null ? getName().hashCode() : 0);
        result = 31 * result + (getDesignerId() != null ? getDesignerId().hashCode() : 0);
        result = 31 * result + (getStyle() != null ? getStyle().hashCode() : 0);
        result = 31 * result + (getArea() != null ? getArea().hashCode() : 0);
        result = 31 * result + (getLayout() != null ? getLayout().hashCode() : 0);
        result = 31 * result + (getBudget() != null ? getBudget().hashCode() : 0);
        result = 31 * result + (getPhone() != null ? getPhone().hashCode() : 0);
        result = 31 * result + (getIntro() != null ? getIntro().hashCode() : 0);
        result = 31 * result + (getCreatedTime() != null ? getCreatedTime().hashCode() : 0);
        result = 31 * result + (getStatus() != null ? getStatus().hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "DesignOrder{" +
                "did=" + did +
                ", uid=" + uid +
                ", name='" + name + '\'' +
                ", designerId=" + designerId +
                ", style='" + style + '\'' +
                ", area=" + area +
                ", layout='" + layout + '\'' +
                ", budget=" + budget +
                ", phone='" + phone + '\'' +
                ", intro='" + intro + '\'' +
                ", createdTime=" + createdTime +
                ", status=" + status +
                '}';
    }

    public Integer getDid() {
        return did;
    }

    public void setDid(Integer did) {
        this.did = did;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDesignerId() {
        return designerId;
    }

    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public Integer getArea() {
        return area;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public String getLayout() {
        return layout;
    }

    public void setLayout(String layout) {
        this.layout = layout;
    }

    public Integer getBudget() {
        return budget;
    }

    public void setBudget(Integer budget) {
        this.budget = budget;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}