package com.cy.store.entity;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.pic_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.product_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.kind
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    private Integer kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.path
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.pic_id
     *
     * @return the value of t_pic.pic_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.pic_id
     *
     * @param picId the value for t_pic.pic_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.product_id
     *
     * @return the value of t_pic.product_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.product_id
     *
     * @param productId the value for t_pic.product_id
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.kind
     *
     * @return the value of t_pic.kind
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.kind
     *
     * @param kind the value for t_pic.kind
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.path
     *
     * @return the value of t_pic.path
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.path
     *
     * @param path the value for t_pic.path
     *
     * @mbggenerated Thu Apr 27 15:49:46 CST 2023
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    @Override
    public String toString() {
        return "Picture{" +
                "picId=" + picId +
                ", productId=" + productId +
                ", kind=" + kind +
                ", path='" + path + '\'' +
                '}';
    }
}