package com.cy.store.entity;

import java.util.Date;

public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.category_id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.item_type
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.title
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sell_point
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.num
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Integer num;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.status
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.priority
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.created_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.modified_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.created_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.modified_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    private String modifiedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */

    private Integer kind1;
    private Integer kind2;
    private String color;
    private Integer width;
    private Integer depth;
    private Integer height;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Products)) return false;

        Products products = (Products) o;

        if (getId() != null ? !getId().equals(products.getId()) : products.getId() != null) return false;
        if (getCategory() != null ? !getCategory().equals(products.getCategory()) : products.getCategory() != null)
            return false;
        if (getItemType() != null ? !getItemType().equals(products.getItemType()) : products.getItemType() != null)
            return false;
        if (getTitle() != null ? !getTitle().equals(products.getTitle()) : products.getTitle() != null) return false;
        if (getSellPoint() != null ? !getSellPoint().equals(products.getSellPoint()) : products.getSellPoint() != null)
            return false;
        if (getPrice() != null ? !getPrice().equals(products.getPrice()) : products.getPrice() != null) return false;
        if (getNum() != null ? !getNum().equals(products.getNum()) : products.getNum() != null) return false;
        if (getStatus() != null ? !getStatus().equals(products.getStatus()) : products.getStatus() != null)
            return false;
        if (getPriority() != null ? !getPriority().equals(products.getPriority()) : products.getPriority() != null)
            return false;
        if (getCreatedTime() != null ? !getCreatedTime().equals(products.getCreatedTime()) : products.getCreatedTime() != null)
            return false;
        if (getModifiedTime() != null ? !getModifiedTime().equals(products.getModifiedTime()) : products.getModifiedTime() != null)
            return false;
        if (getCreatedUser() != null ? !getCreatedUser().equals(products.getCreatedUser()) : products.getCreatedUser() != null)
            return false;
        if (getModifiedUser() != null ? !getModifiedUser().equals(products.getModifiedUser()) : products.getModifiedUser() != null)
            return false;
        if (getkind1() != null ? !getkind1().equals(products.getkind1()) : products.getkind1() != null)
            return false;
        if (getkind2() != null ? !getkind2().equals(products.getkind2()) : products.getkind2() != null)
            return false;
        if (getColor() != null ? !getColor().equals(products.getColor()) : products.getColor() != null) return false;
        if (getWidth() != null ? !getWidth().equals(products.getWidth()) : products.getWidth() != null) return false;
        if (getDepth() != null ? !getDepth().equals(products.getDepth()) : products.getDepth() != null) return false;
        return getHeight() != null ? getHeight().equals(products.getHeight()) : products.getHeight() == null;
    }

    @Override
    public int hashCode() {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getCategory() != null ? getCategory().hashCode() : 0);
        result = 31 * result + (getItemType() != null ? getItemType().hashCode() : 0);
        result = 31 * result + (getTitle() != null ? getTitle().hashCode() : 0);
        result = 31 * result + (getSellPoint() != null ? getSellPoint().hashCode() : 0);
        result = 31 * result + (getPrice() != null ? getPrice().hashCode() : 0);
        result = 31 * result + (getNum() != null ? getNum().hashCode() : 0);
        result = 31 * result + (getStatus() != null ? getStatus().hashCode() : 0);
        result = 31 * result + (getPriority() != null ? getPriority().hashCode() : 0);
        result = 31 * result + (getCreatedTime() != null ? getCreatedTime().hashCode() : 0);
        result = 31 * result + (getModifiedTime() != null ? getModifiedTime().hashCode() : 0);
        result = 31 * result + (getCreatedUser() != null ? getCreatedUser().hashCode() : 0);
        result = 31 * result + (getModifiedUser() != null ? getModifiedUser().hashCode() : 0);
        result = 31 * result + (getkind1() != null ? getkind1().hashCode() : 0);
        result = 31 * result + (getkind2() != null ? getkind2().hashCode() : 0);
        result = 31 * result + (getColor() != null ? getColor().hashCode() : 0);
        result = 31 * result + (getWidth() != null ? getWidth().hashCode() : 0);
        result = 31 * result + (getDepth() != null ? getDepth().hashCode() : 0);
        result = 31 * result + (getHeight() != null ? getHeight().hashCode() : 0);
        return result;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getDepth() {
        return depth;
    }

    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.category_id
     *
     * @return the value of t_product.category_id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getCategoryId() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.category_id
     *
     * @param category the value for t_product.category_id
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setCategoryId(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.item_type
     *
     * @return the value of t_product.item_type
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.item_type
     *
     * @param itemType the value for t_product.item_type
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.title
     *
     * @return the value of t_product.title
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.title
     *
     * @param title the value for t_product.title
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sell_point
     *
     * @return the value of t_product.sell_point
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sell_point
     *
     * @param sellPoint the value for t_product.sell_point
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.num
     *
     * @return the value of t_product.num
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.num
     *
     * @param num the value for t_product.num
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setNum(Integer num) {
        this.num = num;
    }





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.status
     *
     * @return the value of t_product.status
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.status
     *
     * @param status the value for t_product.status
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.priority
     *
     * @return the value of t_product.priority
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.priority
     *
     * @param priority the value for t_product.priority
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.created_time
     *
     * @return the value of t_product.created_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.created_time
     *
     * @param createdTime the value for t_product.created_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.modified_time
     *
     * @return the value of t_product.modified_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.modified_time
     *
     * @param modifiedTime the value for t_product.modified_time
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.created_user
     *
     * @return the value of t_product.created_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.created_user
     *
     * @param createdUser the value for t_product.created_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.modified_user
     *
     * @return the value of t_product.modified_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.modified_user
     *
     * @param modifiedUser the value for t_product.modified_user
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    @Override
    public String toString() {
        return "Products{" +
                "id=" + id +
                ", category='" + category + '\'' +
                ", itemType='" + itemType + '\'' +
                ", title='" + title + '\'' +
                ", sellPoint='" + sellPoint + '\'' +
                ", price=" + price +
                ", num=" + num +
                ", status=" + status +
                ", priority=" + priority +
                ", createdTime=" + createdTime +
                ", modifiedTime=" + modifiedTime +
                ", createdUser='" + createdUser + '\'' +
                ", modifiedUser='" + modifiedUser + '\'' +
                ", kind1=" + kind1 +
                ", kind2=" + kind2 +
                ", color='" + color + '\'' +
                ", width=" + width +
                ", depth=" + depth +
                ", height=" + height +
                '}';
    }

    public Integer getkind1() {
        return kind1;
    }

    public void setkind1(Integer kind1) {
        this.kind1 = kind1;
    }

    public Integer getkind2() {
        return kind2;
    }

    public void setkind2(Integer kind2) {
        this.kind2 = kind2;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }
}