package com.cy.store.entity;

public class ProductKind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kind.kid
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    private Integer kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kind.parent
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kind.code
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kind.name
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kind.kid
     *
     * @return the value of t_kind.kid
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kind.kid
     *
     * @param kid the value for t_kind.kid
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kind.parent
     *
     * @return the value of t_kind.parent
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kind.parent
     *
     * @param parent the value for t_kind.parent
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kind.code
     *
     * @return the value of t_kind.code
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kind.code
     *
     * @param code the value for t_kind.code
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kind.name
     *
     * @return the value of t_kind.name
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kind.name
     *
     * @param name the value for t_kind.name
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        return "ProductKind{" +
                "kid=" + kid +
                ", parent=" + parent +
                ", code=" + code +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProductKind)) return false;

        ProductKind that = (ProductKind) o;

        if (getKid() != null ? !getKid().equals(that.getKid()) : that.getKid() != null) return false;
        if (getParent() != null ? !getParent().equals(that.getParent()) : that.getParent() != null) return false;
        if (getCode() != null ? !getCode().equals(that.getCode()) : that.getCode() != null) return false;
        return getName() != null ? getName().equals(that.getName()) : that.getName() == null;
    }

    @Override
    public int hashCode() {
        int result = getKid() != null ? getKid().hashCode() : 0;
        result = 31 * result + (getParent() != null ? getParent().hashCode() : 0);
        result = 31 * result + (getCode() != null ? getCode().hashCode() : 0);
        result = 31 * result + (getName() != null ? getName().hashCode() : 0);
        return result;
    }
}