package com.cy.store.entity;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.rid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.oid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.pid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.uid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.score
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Byte score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private String review;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.created_user
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_review.created_time
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.rid
     *
     * @return the value of t_review.rid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.rid
     *
     * @param rid the value for t_review.rid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.oid
     *
     * @return the value of t_review.oid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.oid
     *
     * @param oid the value for t_review.oid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.pid
     *
     * @return the value of t_review.pid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.pid
     *
     * @param pid the value for t_review.pid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.uid
     *
     * @return the value of t_review.uid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.uid
     *
     * @param uid the value for t_review.uid
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.score
     *
     * @return the value of t_review.score
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.score
     *
     * @param score the value for t_review.score
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.review
     *
     * @return the value of t_review.review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.review
     *
     * @param review the value for t_review.review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setReview(String review) {
        this.review = review == null ? null : review.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.created_user
     *
     * @return the value of t_review.created_user
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.created_user
     *
     * @param createdUser the value for t_review.created_user
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_review.created_time
     *
     * @return the value of t_review.created_time
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_review.created_time
     *
     * @param createdTime the value for t_review.created_time
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}