package com.cy.store.mapper;

import com.cy.store.entity.District;
import com.cy.store.entity.ProductKind;

import java.util.List;

public interface ProductKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kind
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    int deleteByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kind
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    int insert(ProductKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kind
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    ProductKind selectByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kind
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    List<ProductKind> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kind
     *
     * @mbggenerated Tue May 02 16:13:11 CST 2023
     */
    int updateByPrimaryKey(ProductKind record);

    List<ProductKind> findByParent(String parent);

    String findNameByCode(String code);
}