package com.cy.store.mapper;

import com.cy.store.entity.Products;
import java.util.List;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    Products selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    List<Products> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 26 10:41:32 CST 2023
     */
    int updateByPrimaryKey(Products record);

    /**
     * 多条件筛选
     * @param kind1
     * @param kind2
     * @param color
     * @param material
     * @param minWidth
     * @param maxWidth
     * @param minDepth
     * @param maxDepth
     * @param minHeight
     * @param maxHeight
     * @return
     */
    List<Products> selectByMultiple(Integer kind1, Integer kind2,Integer priceSort, String color, String material, Integer minPrice, Integer maxPrice, Integer minWidth, Integer maxWidth, Integer minDepth, Integer maxDepth, Integer minHeight, Integer maxHeight);
}