package com.cy.store.mapper;

import com.cy.store.entity.Review;
import com.cy.store.vo.ReviewVO;

import java.util.List;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    Review selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_review
     *
     * @mbggenerated Mon May 08 18:03:19 CST 2023
     */
    int updateByPrimaryKey(Review record);

    /**
     * 选择指定商品的评论
     * @param pid
     * @return
     */
    List<Review> selectByPid(Integer pid);

    Float findAvgScore(Integer pid);

    Integer CountReviewByPidAndScore(Integer pid, Integer score);

    Integer CountReviewByPid(Integer pid);

    List<ReviewVO> findVOByPid(Integer pid);
}